---
- name: Time configuration
  hosts: poznan
  tasks:
    - name: Time change
      lineinfile:
        path: /etc/chrony.conf
        regexp: "^pool 2."
        line: "server base iburst"
      notify: Service restart
      changed_when: True
  
  handlers:
    - name: Service restart
      systemd:
        name: chronyd
        state: restarted
