---
- name: test
  hosts: poznan
  tasks:
    - name: Task 1
      debug:
        msg: "Task 1"
    
    - name: Task 2
      debug:
        msaaag: "Task 2"
      ignore_errors: yes

    - name: Task 3
      debug:
        msg: "Task 3"
