---
- name: web server implementation
  hosts: servers
  vars_files: templates_vars.yml
  tasks:
    - name: motd deployment
      template:
        src: issue.j2
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644
