---
- name: db installation
  hosts: db
  tasks:
    - name: mariadb installation
      dnf:
        name: mariadb-server
        state: latest

    - name: db startup
      systemd:
        name: mariadb
        state: started
        enabled: yes

- name: web server installation
  hosts: web
  tasks:
    - name: httpd installation
      dnf:
        name: httpd
        state: latest

    - name: apache startup
      systemd:
        name: httpd
        state: started
        enabled: yes
