---
- name: User Creation
  hosts: all
  vars:
    users:
      - lolek
      - bolek
      - krzysiek
  tasks:
    
    - name: Info
      debug:
        msg: "Users which will be added: {{ users | join(', ') }}"
    
    - name: Adding Users
      user:
        name: "{{ item }}"
        state: present
        password: "{{ (item + '123') | password_hash('sha512') }}"
      loop: "{{ users }}"
