---
- name: WWW web server implementation for gdynia host
  hosts: gdansk
  tasks:

    - name: httpd installation
      yum:
        name: httpd
        state: latest

    - name: index.html creation
      copy:
        content: "Hello Apache\n"
        dest: /var/www/html/inex.html

    - name: httpd startup
      service:
        name: httpd
        state: started
        enabled: true

    - name: firewall for port 80/tcp
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: true

- name: WWW web server implementation for krakow host
  hosts: katowice
  tasks:

    - name: httpd installation
      yum:
        name: httpd
        state: latest

    - name: index.html creation
      copy:
        content: "Hello Apache\n"
        dest: /var/www/html/index.html

    - name: httpd startup
      service:
        name: httpd
        state: started
        enabled: true

    - name: firewal for port 80/tcp - turn off
      firewalld:
        port: 80/tcp
        permanent: yes
        state: disabled
        immediate: true

- name: Service test
  hosts: localhost
  tasks:

    - name: gdansk connection test
      uri:
        url: http://gdansk
        return_content: yes
        status_code: 200

    - name: katowice connection test
      uri:
        url: http://katowice
        return_content: yes
        status_code: 200
