---
- name: DB install
  hosts: all
  tasks:
    - name: Installation
      dnf:
        name: mariadb-server
        state: latest
      failed_when: ansible_memfree_mb < 1250

    - name: DB startup
      systemd:
        name: mariadb
        state: started
        enabled: yes
