---
- name: /etc backup
  hosts: all
  tasks:
    - name: /etc_backup folder creation
      file:
        path: /etc_backup
        owner: root
        group: root
        mode: 0644
        state: directory

    - name: archiving /etc to /etc_backup/etc.zip
      archive:
        path: /etc
        dest: /etc_backup/etc.zip
        format: zip

    - name: downloading archives from hosts to base
      fetch:
        src: /etc_backup/etc.zip
        dest: /tmp
