---
- name: vsftpd implementation
  hosts: katowice
  vars_files: vars.yml
  tasks:
    - name: "{{ ftp_package }} installation"
      dnf:
        name: "{{ ftp_package }}"
        state: latest
    - name: "{{ ftp_service }} startup and autostart"
      service:
        name: "{{ ftp_service }}"
        state: started
        enabled: true
    - name: "firewall for {{ ftp_firewall }}"
      firewalld:
        service: "{{ ftp_firewall }}"
        permanent: yes
        state: enabled
        immediate: true
