---
- name: server vsftpd on gdansk server
  hosts: gdansk
  tasks:

    - name: vsftpd installation
      yum:
        name: vsftpd
        state: latest

    - name: vsftpd startup
      service:
        name: vsftpd
        state: started
        enabled: true

    - name: firewall for ftp
      firewalld:
        service: ftp
        permanent: yes
        state: enabled
        immediate: true

- name: ftp installation on katowice host
  hosts: katowice
  tasks:

    - name: ftp installation
      yum:
        name: ftp
        state: latest 
