---
- name: httpd startup on unspecified port
  hosts: all
  vars:
    http_port: 12345
  tasks:
    - name: httpd installation
      dnf:
        name: httpd
        state: latest

    - name: httpd autostartup
      service:
        name: httpd
        state: started
        enabled: yes

    - name: adding port "{{ http_port }}" to httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        insertafter: '^Listen'
        line: "Listen {{ http_port }}"
      notify:
        - restart apache

    - name: adding port "{{ http_port }}" to SELinux configuration
      seport:
        ports: "{{ http_port }}"
        proto: tcp
        setype: http_port_t
        state: present
      notify:
        - restart apache

    - name: adding port "{{ http_port }}" to firewall
      firewalld:
        port: "{{ http_port }}/tcp"
        state: enabled
        permanent: yes
        immediate: true

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
