---
- name: ...
  hosts: all
  vars:
    min_ram_mb: 200
    supported_distros:
      - Debian
      - RedHat
      - Rocky
  tasks:
  - name: ...
    dnf:
      name: mariadb
      state: latest
    when:
      - ansible_memfree_mb >= min_ram_mb
      - ansible_distribution in supported_distros

  - name: ...
    debug:
      msg: "{{ inventory_hostname }} has not enough RAM - {{ ansible_memtotal_mb }}MB and should have at least {{ min_ram_mb }}MB"

  - name: ...
    debug:
      msg: "{{ inventory_hostname }} is {{ ansible_distribution }} which is not supported"
    when:
      - ansible_distribution not in supported_distros
