---
- name: Users management
  become: True
  hosts: servers
  vars_files: user_list.yml
  tasks:
    - name: Group creation
      group:
        name: '{{ item }}'
        state: present
      loop:
        - administrator
        - admin

    - name: User creation
      user:
        name: '{{ item.name }}'
        state: present
        group: '{{ item.group }}'
      loop: '{{ users }}'
