---
- name: ...
  hosts: all
  vars:
    package_name: mariadb-server
  tasks:

  - name: ...
    dnf:
      name: '{{ package_name }}'
      state: latest
    when: ansible_memfree_mb >= 1250

  - name: ...
    systemd:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_memfree_mb >= 1250
