---
# Service related tasks

- name: Package installation
  dnf:
    name: "{{ package }}"
    state: latest

- name: Service startup
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service }}"
