#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/db
- name: Install db
  ansible.builtin.apt:
    name: "{{ db_server }}"
    state: latest
    update_cache: true
  notify:
    - start db

- name: Display installed db name
  ansible.builtin.debug:
    msg: "{{db_server}}"
