#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/php
- include_tasks: service.yml
- include_tasks: firewall.yml
- include_tasks: app.yml
- include_tasks: config.yml
- include_tasks: selinux.yml
