---
- name: Blocks
  hosts: server01
  vars:
    package: nginxxx
  tasks:
    - block:
        - name: Trying to install {{ package }}
          ansible.builtin.apt:
            name: "{{ package  }}"
            state: present
            update_cache: true
      rescue:
        - name: Rescue block
          ansible.builtin.debug:
            msg: "Executes on rescue, when task inside a block ends with an error!"
      always:
        - name: Always block
          ansible.builtin.debug:
            msg: "I am always executing!"

    - name: Next task
      ansible.builtin.debug:
        msg: "Next task was started..."
