---
- name: Conditionals
  hosts: db
  vars:
    min_ram_mb: 200
    supported_distros:
      - RedHat
      - Fedora
      - CentOS
  tasks:
  - name: Install db
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when:
      - ansible_memtotal_mb < min_ram_mb
      - ansible_distribution in supported_distros

  - name: "error: Not enough RAM"
    ansible.builtin.debug:
      msg: "{{ inventory_hostname }} has {{ ansible_memtotal_mb }}Mb of total RAM and should have at least {{ min_ram_mb }}Mb"
    when:
      - ansible_memtotal_mb < min_ram_mb

  - name: "error: Unsupported distribution"
    ansible.builtin.debug:
      msg: "{{ inventory_hostname }} distribution ({{ ansible_distribution }}) is not supported"
    when:
      - ansible_distribution not in supported_distros
