---
- name: Error handling
  hosts: server01
  vars:
    package: nginx
  tasks:
    - name: Trying to install {{ package }}
      ansible.builtin.apt:
        name: "{{ package  }}"
        state: present
        update_cache: true
      failed_when: ansible_memfree_mb < 1000

    - name: Next Task
      ansible.builtin.debug:
        msg: "Next next task will not be executed"
