---
- name: Handlers
  hosts: all
  tasks:
    - name: Installing Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      notify:
        - first handler (Restarting Nginx)
        - second handler (Removing Nginx)

    - name: Task after handlers
      ansible.builtin.debug:
        msg: "I was executed before handlers"

  handlers:
    - name: first handler (Restarting Nginx)
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted

    - name: second handler (Removing Nginx)
      ansible.builtin.apt:
        name: nginx
        state: absent
