---
- name: Handlers
  hosts: web
  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      notify:
        - restart nginx

    - name: Installing nano
      apt:
        name: nano
        state: present
        update_cache: yes
      notify:
        - restart nginx

    - name: Installing Vim
      apt:
        name: vim
        state: present
        update_cache: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
