---
- name: Loops
  hosts: db
  vars:
    groups:
      - dev
      - admin
    users:
      - name: "jan"
        group: "admin"
      - name: "bob"
        group: "dev"
  tasks:
    - name: Group creation
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ groups }}"

    - name: User creation
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        group: "{{ item.group }}"
      loop: "{{ users }}"
