---
- name: Loops
  hosts: db
  tasks:
    - name: Group creation
      ansible.builtin.group:
        name:  "{{ item }}"
        state: present
      loop:
        - dev
        - admin

    - name: User creation
      ansible.builtin.user:
        name: "{{ item.user }}"
        state: present
        name: "{{ item.group }}"
      loop:
        - { user: jan, group: dev }
        - { user: bob, group: admin }
