---
- name: Register
  hosts: web
  tasks:
    - name: Installing curl
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes

    - name: curl httpbin.org API
      ansible.builtin.shell:
        cmd: 'curl -X GET "https://httpbin.org/get" -H  "accept: application/json"'
      register: curl_output
    
    - name: curl request response
      ansible.builtin.debug: var=curl_output.stdout_lines

    - name: Removing curl
      ansible.builtin.apt:
        name: curl
        state: absent
