---
- name: Variables
  hosts: server01
  tasks:
    - name: Display 1st variable
      debug:
        msg: "{{ http_port }}"
    - name: Display 2nd variable
      debug:
        msg: "{{ server_name }}"
