---
- name: Variables
  hosts: server01
  tasks:
    - name: Display 1st variable
      ansible.builtin.debug:
        msg: "{{ http_port }}"

    - name: Display 2nd variable
      ansible.builtin.debug:
        msg: "{{ server_name }}"
